// BadgeMedallion.swift
//
// Every badge in the app is drawn here, in one of two ways.
//
// DRAWN ART (redesign-badge-art): when the caller passes the badge's
// `family` and that family is switched on (`BadgeArt.enabledFamilies`), the
// badge is a FRAME image (shape = family, trim and colour = rarity) with a
// MOTIF image on top (from the badge's SF Symbol, via Gamification's
// BadgeArtCatalog). Both are SVG imagesets under Assets.xcassets/BadgeArt,
// generated by tools/docs/build-badge-assets.mjs from ios/BadgeArt and
// approved by the owner on docs/guide/badges.html, which uses the same
// files and the same motif box. A locked badge is the frame as a grey
// silhouette with a lock (a question mark for a hidden secret) and no
// motif. Every family is switched on; `BadgeArt.enabledFamilies` can
// switch one back to the disc without touching a call site.
//
// THE DISC (the original, and the fallback): a base disc, a rarity-coloured
// rim, an inner highlight ring, a shine for the top two rarities, and the
// SF Symbol; locked is a plain grey disc with a lock. Used when no family
// is passed, the family is not switched on yet, the symbol has no motif,
// or an image is missing from the bundle -- the app never shows an empty
// badge (design D5).
//
// Deliberately NOT in Shared/Theme.swift: this needs Gamification's
// `AchievementRarity` type, and Gamification is app-only -- not linked into
// the widget extension target, which also compiles Theme.swift (see
// CLAUDE.md's architecture section). Importing Gamification there would
// break the widget build. This file's own small rarity palette lives here
// instead, picked to sit alongside Theme's existing hues without colliding
// with the macro colours (carbs/protein/fat), which already mean something
// else everywhere else in the app.

import SwiftUI
import UIKit
import Gamification

/// Which badge families use the drawn art (redesign-badge-art tasks
/// 3.2/3.3): all of them. Streak went first; taking a family out of this
/// set puts it back on the disc if it misdraws on a device.
enum BadgeArt {
    static let enabledFamilies = Set(BadgeFamily.allCases)

    /// Where the motif sits in the frame's 64-unit box: x, y, side. The same
    /// numbers as tools/docs/build-badge-gallery.mjs's MOTIF_BOX.
    static func motifBox(_ family: BadgeFamily) -> (x: CGFloat, y: CGFloat, side: CGFloat) {
        switch family {
        case .records: return (19.5, 14.5, 25)
        case .levels: return (20.5, 22, 23)
        case .secrets: return (19, 13, 26)
        case .journeys: return (18.5, 15, 27)
        default: return (18, 18, 28)
        }
    }
}

struct BadgeMedallion: View {
    let symbol: String
    let rarity: AchievementRarity
    let isLocked: Bool
    var size: CGFloat = 60
    /// The badge's frame shape; `nil` draws the disc.
    var family: BadgeFamily? = nil

    @Environment(\.accessibilityReduceMotion) private var reduceMotion
    @State private var revealed = false

    private var showsShine: Bool { !isLocked && rarity >= .epic }

    /// The frame and motif to draw, or `nil` for the disc (see the header).
    private var art: (family: BadgeFamily, frame: String, motif: String?)? {
        guard let family, BadgeArt.enabledFamilies.contains(family) else { return nil }
        let frame = BadgeArtCatalog.frameAssetName(family: family, rarity: rarity)
        guard UIImage(named: frame) != nil else { return nil }
        if isLocked { return (family, frame, nil) }
        guard let name = BadgeArtCatalog.motif(forSymbol: symbol) else { return nil }
        let motif = BadgeArtCatalog.motifAssetName(name)
        guard UIImage(named: motif) != nil else { return nil }
        return (family, frame, motif)
    }

    var body: some View {
        ZStack {
            if let art {
                drawn(art.family, frame: art.frame, motif: art.motif)
            } else {
                base
                if showsShine { shine }
                glyph
            }
        }
        .frame(width: size, height: size)
        .onAppear { revealed = true }
    }

    @ViewBuilder
    private func drawn(_ family: BadgeFamily, frame: String, motif: String?) -> some View {
        if let motif {
            let box = BadgeArt.motifBox(family)
            let unit = size / 64
            Image(frame)
                .resizable()
                .frame(width: size, height: size)
            Image(motif)
                .resizable()
                .frame(width: box.side * unit, height: box.side * unit)
                .offset(x: (box.x + box.side / 2 - 32) * unit, y: (box.y + box.side / 2 - 32) * unit)
            if showsShine {
                shine.mask {
                    Image(frame).resizable().frame(width: size, height: size)
                }
            }
        } else {
            // Locked: the family's shape only, as one flat grey.
            Image(frame)
                .renderingMode(.template)
                .resizable()
                .frame(width: size, height: size)
                .foregroundStyle(Color.primary.opacity(0.16))
            Image(systemName: symbol == "questionmark" ? "questionmark" : "lock.fill")
                .font(.system(size: size * 0.3, weight: .semibold))
                .foregroundStyle(Color.secondary)
        }
    }

    private var base: some View {
        Circle()
            .fill(isLocked ? AnyShapeStyle(Color.primary.opacity(0.07)) : AnyShapeStyle(RarityPalette.fill(rarity)))
            .overlay {
                Circle()
                    .strokeBorder(isLocked ? Color.primary.opacity(0.16) : RarityPalette.rim(rarity), lineWidth: max(1.5, size * 0.045))
            }
            .overlay {
                // A thin inner highlight ring reads as "metal catching
                // light" -- the one cue that most separates a real medallion
                // from a flat filled circle.
                Circle()
                    .strokeBorder(Color.white.opacity(isLocked ? 0 : 0.32), lineWidth: 1)
                    .padding(size * 0.09)
            }
            .shadow(color: isLocked ? .clear : RarityPalette.rim(rarity).opacity(0.35), radius: size * 0.09, y: size * 0.03)
    }

    /// A one-shot diagonal shine that plays in when the badge first appears
    /// unlocked, reserved for `.epic`/`.legendary` so the very best badges
    /// visibly stand out from the rest of the grid. Respects Reduce Motion
    /// by simply not animating -- the shine still ends up in its final,
    /// static position either way (same pattern as `ProgressRing`/
    /// `MacroBar`: `.animation(reduceMotion ? nil : ..., value:)`).
    private var shine: some View {
        Circle()
            .fill(
                LinearGradient(
                    colors: [.white.opacity(0.5), .white.opacity(0)],
                    startPoint: .topLeading,
                    endPoint: .bottomTrailing
                )
            )
            .mask { Circle() }
            .rotationEffect(.degrees(revealed ? 0 : -30))
            .opacity(revealed ? 1 : 0)
            .animation(reduceMotion ? nil : .easeOut(duration: 0.55).delay(0.1), value: revealed)
            .allowsHitTesting(false)
    }

    private var glyph: some View {
        Image(systemName: isLocked ? "lock.fill" : symbol)
            .font(.system(size: size * 0.42, weight: .semibold))
            .foregroundStyle(isLocked ? Color.secondary : .white)
    }
}

/// `BadgeMedallion`'s colour ramp for `AchievementRarity` -- see this
/// file's header for why it isn't in `Shared/Theme.swift`.
private enum RarityPalette {
    static func fill(_ rarity: AchievementRarity) -> LinearGradient {
        let (top, bottom) = colors(rarity)
        return LinearGradient(colors: [top, bottom], startPoint: .top, endPoint: .bottom)
    }

    static func rim(_ rarity: AchievementRarity) -> Color {
        colors(rarity).1
    }

    /// (top, bottom) stops -- bottom doubles as the rim colour so the rim
    /// always reads as "the deep end of the same metal", not an unrelated
    /// outline colour.
    private static func colors(_ rarity: AchievementRarity) -> (Color, Color) {
        switch rarity {
        case .common:
            // Brushed pewter.
            return (Color(red: 0.70, green: 0.72, blue: 0.76), Color(red: 0.47, green: 0.49, blue: 0.53))
        case .uncommon:
            // Patinated bronze-green.
            return (Color(red: 0.42, green: 0.71, blue: 0.54), Color(red: 0.19, green: 0.49, blue: 0.35))
        case .rare:
            // Polished steel-blue.
            return (Color(red: 0.40, green: 0.62, blue: 0.94), Color(red: 0.18, green: 0.38, blue: 0.75))
        case .epic:
            // Amethyst.
            return (Color(red: 0.66, green: 0.46, blue: 0.93), Color(red: 0.44, green: 0.24, blue: 0.73))
        case .legendary:
            // Warm gold, deliberately close in hue to Theme's own ember/
            // accent so a legendary badge still feels like it belongs to
            // this app's palette rather than a bolted-on rainbow tier.
            return (Color(red: 0.99, green: 0.80, blue: 0.30), Color(red: 0.92, green: 0.50, blue: 0.15))
        }
    }
}

#Preview("BadgeMedallion -- unlocked, all rarities") {
    HStack(spacing: 16) {
        ForEach(AchievementRarity.allCases, id: \.self) { rarity in
            VStack(spacing: 6) {
                BadgeMedallion(symbol: "flame.fill", rarity: rarity, isLocked: false, size: 60)
                Text(rarity.displayName).font(.caption2)
            }
        }
    }
    .padding()
}

#Preview("BadgeMedallion -- locked vs unlocked") {
    HStack(spacing: 24) {
        BadgeMedallion(symbol: "crown.fill", rarity: .legendary, isLocked: true, size: 80)
        BadgeMedallion(symbol: "crown.fill", rarity: .legendary, isLocked: false, size: 80)
    }
    .padding()
}
